circlefin/malachite

README.md

feat(docs): Added acknowledgement section in main readme

---

code/crates/core-consensus/src/effect.rs
code/crates/core-consensus/src/handle/proposal.rs
code/crates/core-consensus/src/handle/timeout.rs
code/crates/core-consensus/src/handle/vote.rs
code/crates/engine/src/consensus.rs

Closes: https://github.com/informalsystems/malachite/issues/716
---

chore(code): Rename `Persist` effects to `WalAppend`

---

CONTRIBUTING.md

fix(docs): Telegram link in `CONTRIBUTING.md`

---

specs/consensus/overview.md

Reviewed the original content and adapted it for being easier to read.
The next step is to address there concerns listed in #367.
---

feat(spec): Improvements and fixes in consensus overview

---

.github/workflows/need-triage-label.yml

Closes: https://github.com/informalsystems/malachite/issues/732

chore: Auto-label issues not from code owners with `need-triage` label

---

code/crates/starknet/test/src/lib.rs

chore(code/test): Fix full node tests

---

code/crates/test/cli/src/cmd/start.rs
code/crates/test/cli/src/metrics.rs
code/examples/channel/src/metrics.rs
code/examples/channel/src/node.rs
code/examples/channel/src/store.rs

feat(code): Added metrics to example channel app's store

---

.github/workflows/rust.yml
code/Cargo.toml
code/crates/peer/Cargo.toml
code/crates/peer/src/lib.rs

Addressed FIXME on [code/crates/peer/src/lib.rs:21](https://github.com/informalsystems/malachite/blob/7e121597d8be94b8a720a4c8fcd4bed832e4d0ab/code/crates/peer/src/lib.rs#L21)
---

feat(code): Make `peer` crate `no_std` compatible

---

code/crates/core-consensus/src/handle/propose.rs
code/crates/core-consensus/src/input.rs
code/crates/core-consensus/src/types.rs
code/crates/engine/src/consensus.rs
code/crates/engine/src/host.rs
code/crates/engine/src/util/events.rs
code/crates/starknet/test/src/lib.rs
code/crates/starknet/test/src/tests/wal.rs

chore(code): Cleanup proposal-related types

---

code/crates/starknet/host/src/mempool.rs
code/crates/starknet/host/src/spawn.rs

Addresses TODOs on [/code/crates/starknet/host/src/mempool.rs](https://github.com/informalsystems/malachite/tree/main/code/crates/starknet/host/src/mempool.rs#L24-L25)
---

feat(code): refactored parameters of `spawn_mempool_actor()` function in starknet host

---

code/examples/channel/src/app.rs
code/examples/channel/src/node.rs
code/examples/channel/src/state.rs

This PR aims to close: #773. 
---

feat(code): Check proposal validity in the example app

---

code/crates/core-state-machine/src/traces/line.rs

chore(code): Fix consensus traces

---

code/Cargo.lock
code/crates/starknet/test/mbt/src/tests/streaming.rs
code/crates/starknet/test/mbt/src/tests/streaming/runner.rs
code/crates/starknet/test/mbt/src/tests/streaming/utils.rs

chore(code): Fix clippy warnings

---

specs/consensus/pseudo-code.md

fix(spec/consensus): fixes on Tendermint pseudo-code

---

code/crates/engine/src/consensus.rs
code/crates/engine/src/network.rs

Closes: #XXX
The Network actor needs to notify new subscribers of the listening addresses and the connected peers, otherwise if the Consensus actor ends up starting after the Network actor, it will not subscribe to network events in time, therefore never getting the Listening notification and never starting.
---

fix(code/network): Notify new subscribers of listen addresses and connected peers

---

specs/consensus/message-handling.md

fix(spec/consensus): fixed link in `message-handling.md`

---

code/crates/core-consensus/src/handle/vote.rs
code/crates/engine/src/consensus.rs
code/crates/engine/src/sync.rs
code/crates/sync/src/handle.rs
code/crates/sync/src/state.rs
code/crates/test/app/src/app.rs
code/examples/channel/src/app.rs

fix(code): Fix various sync-related bugs seen in testnet

---

code/crates/app-channel/src/msgs.rs
code/crates/test/app/src/app.rs
code/crates/test/app/src/state.rs
code/crates/test/proto/consensus.proto
code/crates/test/src/proposal_part.rs
code/crates/test/tests/it/n3f0_consensus_mode.rs
code/crates/test/tests/it/value_sync.rs
code/crates/test/tests/it/vote_sync.rs
code/crates/test/tests/it/wal.rs
code/examples/channel/src/app.rs
code/examples/channel/src/state.rs

fix(code/app): Add the POL round to `ProposalInit` message of the example and test applications

---

code/Cargo.lock
code/crates/core-consensus/src/handle/decide.rs
code/crates/core-consensus/src/handle/driver.rs
code/crates/core-consensus/src/state.rs
code/crates/core-driver/src/driver.rs
code/crates/core-driver/src/mux.rs
code/crates/test/app/src/app.rs
code/crates/test/tests/it/value_sync.rs
code/crates/test/tests/it/vote_sync_bcast.rs
code/crates/test/tests/it/wal.rs
code/scripts/spawn.bash

chore(code): Undo vote equivocation hack

---

code/crates/core-consensus/src/handle/vote.rs
code/crates/engine/src/consensus.rs

fix(code): Full nodes send empty commit certificates when deciding

---

code/Cargo.lock
code/crates/app/src/spawn.rs
code/crates/config/src/lib.rs
code/crates/network/src/lib.rs
code/crates/starknet/host/src/node.rs
code/crates/starknet/host/src/spawn.rs
code/crates/starknet/test/src/lib.rs
code/crates/test/app/src/node.rs
code/crates/test/mempool/Cargo.toml
code/crates/test/mempool/src/lib.rs
code/crates/test/tests/it/main.rs
code/examples/channel/src/node.rs

fix(code): Remove transport argument in p2p config

---

code/Cargo.lock
code/crates/core-consensus/src/handle/proposed_value.rs
code/crates/core-driver/src/driver.rs
code/crates/core-state-machine/src/output.rs
code/crates/core-state-machine/src/state.rs
code/crates/core-state-machine/src/state_machine.rs
code/crates/core-types/src/context.rs
code/crates/starknet/p2p-types/src/context.rs
code/crates/test/Cargo.toml
code/crates/test/app/src/node.rs
code/crates/test/framework/src/node.rs
code/crates/test/mbt/src/tests/consensus/runner.rs
code/crates/test/src/context.rs
code/crates/test/src/middleware.rs
code/crates/test/tests/it/main.rs
code/crates/test/tests/it/wal.rs
code/examples/channel/src/node.rs

feat(code/test): Add concept of middleware to change from the tests how votes and proposals are built

---

code/crates/engine/src/consensus.rs
code/crates/starknet/host/src/node.rs
code/crates/starknet/host/src/spawn.rs
code/crates/starknet/p2p-types/src/address.rs
code/crates/starknet/test/src/lib.rs
code/scripts/spawn.bash

feat(code/starknet): Derive address from public key

---

code/crates/network/src/lib.rs
code/crates/test/mempool/src/lib.rs

fix(code/network): Support both `quic` and `quic-v1` protocol specifiers in multiaddr

---

code/crates/discovery/src/handlers/dial.rs

Closes: #941
The issue was resolved on branch `anca/starknet_interop` (#868), but not on main.
---

fix(code): Fibonacci backoff

---

README.md

chore(docs): Add Protobuf to the requirements list

---

code/Cargo.toml
code/crates/core-consensus/src/handle/vote.rs
code/crates/core-consensus/src/state.rs

chore(code): Get the precommits from the driver instead of storing in consensus state

---

code/crates/core-consensus/src/handle/propose.rs

chore(code): Add proposer check when a value to propose is received

---

code/crates/sync/src/state.rs

chore(code): Send vote requests to peers at same tip height

---

code/crates/config/src/lib.rs
code/crates/starknet/host/src/host/starknet.rs
code/crates/starknet/host/src/mempool_load.rs
code/crates/starknet/host/src/spawn.rs
code/crates/starknet/test/src/lib.rs
code/crates/test/framework/src/params.rs

chore(code): Cleanup mempool config

---

README.md

Every week I hear someone mis-pronounce the name. Having it on the main readme hopefully helps.
---

fix(docs): Update README.md to include a pronunciation guide

---

.github/pull_request_template.md

From now on, let's try to track notable release notes and breaking changes.

chore(admin): Update PR template with release notes and breaking changes

---

BREAKING_CHANGES.md
RELEASE_NOTES.md
code/crates/app-channel/src/msgs.rs
code/crates/core-consensus/src/effect.rs
code/crates/engine/src/consensus.rs
code/crates/engine/src/host.rs
code/crates/starknet/host/src/actor.rs
code/crates/test/app/src/app.rs
code/examples/channel/src/app.rs

chore(code): make `GetValidatorSet` reply optional

---

code/crates/starknet/host/src/actor.rs
code/crates/starknet/host/src/block_store.rs
code/crates/starknet/host/src/host/state.rs
code/crates/test/app/src/node.rs
code/crates/test/app/src/store.rs
code/examples/channel/src/node.rs
code/examples/channel/src/store.rs
docs/tutorials/channels.md

Closes: #1013
I'm sorry but I don't know how to run UTs for this change (so I don't know yet if I've broken any).
Let me know if there's another place that needs the same fix (I've done a search based on some text within the function and that's all I found).
Also, please let me know anything else I need to do to conform to the process of submitting a PR in Malachite.
---

fix(code): Make `Store`/`BlockStore` "open" method async in example, test app, and starknet

---

code/crates/engine/src/consensus.rs
code/crates/engine/src/network.rs
code/crates/starknet/host/src/codec.rs
code/crates/starknet/p2p-proto/proto/p2p/proto/consensus/liveness.proto
code/crates/test/proto/liveness.proto
code/crates/test/src/codec/proto/mod.rs

chore(code): Send rebroadcast votes to the liveness topic

---

code/examples/channel/src/state.rs
codecov.yml

ci: Restore Codecov config

---

code/examples/channel/README.md

Closes: #1024 
This pull request updates the README.md for the channel example to improve clarity and provide necessary context for running the application.
Added a Prerequisites section with a reference to the main Setup guide.
Adding a direct link to the central setup instructions should be sufficient for now and helps prevent users from attempting to build the example without completing the required setup steps.
This approach also avoids duplication, which is particularly helpful given that setup instructions may change frequently. In the future, a more comprehensive setup guide as part of broader documentation could replace this reference.
It's a very low-priority change — more of a low-hanging fruit — and shouldn't take focus away from core work
[conv-commits]: …

chore(docs): add prerequisites section to the channel example README 

---

.github/workflows/coverage.yml
code/crates/app/src/lib.rs

ci: Fix coverage upload to Codecov

---

code/crates/test/tests/it/middlewares.rs
code/crates/test/tests/it/wal.rs

test: Fix flaky test

---

code/crates/engine/src/network.rs
code/crates/starknet/host/src/block_store.rs
code/crates/test/app/src/store.rs
code/crates/test/tests/it/middlewares.rs
code/crates/wal/benches/wal.rs
code/crates/wal/src/file.rs
code/crates/wal/tests/it/crashes.rs
code/examples/channel/src/store.rs

chore(code): Fix clippy warnings on Rust 1.87

---

code/Cargo.toml
code/clippy.toml

chore(code): Bump MSRV to Rust 1.85

---

.github/workflows/coverage.yml
code/crates/app/src/lib.rs
codecov.yml

ci: Upload coverage to Codecov at once

---

code/crates/core-consensus/src/handle/driver.rs
code/crates/core-driver/src/driver.rs
code/crates/core-votekeeper/src/keeper.rs

feat(code): Prune votes and polka certificates that are from lower rounds than node's `locked_round`

---

code/Cargo.lock
code/Cargo.toml
code/crates/core-consensus/src/handle/proposed_value.rs
code/crates/core-types/Cargo.toml
code/crates/core-types/src/value.rs
code/crates/engine/src/consensus.rs
code/crates/engine/src/sync.rs
code/crates/sync/Cargo.toml
code/crates/sync/src/handle.rs

feat(code/sync): Re-request value when we get an invalid value

---

code/crates/discovery/src/handlers/dial.rs
code/crates/network/src/lib.rs

chore(code/discovery): Dial retrial issue

---

code/crates/network/src/lib.rs

Closes: https://github.com/informalsystems/malachite/issues/1102
---

fix(code/network): Fix handling of liveness messages with `broadcast` p2p protocol

---

code/crates/engine/src/consensus.rs
code/crates/sync/src/handle.rs
code/crates/sync/src/state.rs
code/crates/test/tests/it/value_sync.rs

feat(code/sync): Requests FSM

---

code/crates/engine/src/consensus.rs

fix(code): Emit error instead of panic when validator set is empty

---

BREAKING_CHANGES.md
RELEASE_NOTES.md
code/crates/core-consensus/src/effect.rs
code/crates/core-consensus/src/handle/rebroadcast_timeout.rs
code/crates/engine/src/consensus.rs
code/crates/engine/src/util/events.rs
code/crates/test/framework/src/node.rs

chore(code)!: Rename `Effect::RebroadcastVote` to `Effect::RepublishVote`

---

code/clippy.toml
code/crates/core-consensus/src/util/bounded_queue.rs
code/crates/core-driver/src/driver.rs
code/crates/engine/src/consensus.rs
code/crates/network/test/src/lib.rs
code/crates/starknet/host/src/node.rs
code/crates/starknet/p2p-types/src/address.rs
code/crates/starknet/test/mbt/src/tests/streaming/runner.rs
code/crates/starknet/test/src/lib.rs
code/crates/sync/src/scoring.rs
code/crates/test/app/src/node.rs
code/crates/test/mbt/src/tests/consensus/runner.rs
code/crates/test/mbt/src/tests/votekeeper.rs
code/crates/test/mbt/src/tests/votekeeper/runner.rs
code/crates/test/src/address.rs
code/crates/test/tests/it/main.rs
code/crates/wal/benches/wal.rs
code/crates/wal/tests/it/stress.rs
code/examples/channel/src/node.rs

chore(code): Fix clippy warnings on Rust 1.88

---

code/crates/core-types/src/validator_set.rs
code/crates/test/src/validator_set.rs

chore(code): Remove useless `sort_validators` method, add documentation about sorting validators

---

code/crates/starknet/host/src/actor.rs
code/crates/starknet/host/src/block_store.rs
code/crates/starknet/host/src/block_store/keys.rs
code/crates/sync/src/handle.rs
code/crates/test/app/src/app.rs
code/crates/test/app/src/state.rs
code/crates/test/app/src/store.rs
code/crates/test/app/src/store/keys.rs
code/examples/channel/src/app.rs
code/examples/channel/src/state.rs
code/examples/channel/src/store.rs
code/examples/channel/src/store/keys.rs

feat(app): Buffer proposals for future heights

---

RELEASE_NOTES.md
code/Cargo.lock
code/crates/app/src/spawn.rs
code/crates/config/Cargo.toml
code/crates/config/src/lib.rs
code/crates/discovery/Cargo.toml
code/crates/discovery/src/behaviour.rs
code/crates/engine/src/network.rs
code/crates/network/Cargo.toml
code/crates/network/src/behaviour.rs
code/crates/network/src/lib.rs
code/crates/network/test/src/lib.rs
code/crates/starknet/host/src/spawn.rs
code/crates/sync/Cargo.toml
code/crates/sync/src/behaviour.rs

feat: make protocol names configurable

---

code/crates/starknet/test/src/lib.rs
code/crates/test/tests/it/main.rs

fix(code): Fix deprecation warning on tempfile method

---

code/crates/engine/src/wal.rs
code/crates/engine/src/wal/thread.rs

Closes: #XXX
---
Improve error handling in WAL, making sure that all errors are properly logged.
Also fixes a bug where a reply would not be sent to the consensus actor when the WAL actor receives a mismatched `Append` message, logging `Failed to send Append command to WAL actor: Messaging failed because channel is closed`.
---

fix(code/wal): Improve error handling in WAL

---

.github/workflows/coverage.yml
.github/workflows/publish.yml

* `arduino/setup-protoc`
* `katyo/publish-crates`

chore: use managed actions for certain workflows

---

code/crates/config/src/lib.rs

fix(CCHAIN-539): Enable consensus by default
