circlefin/malachite

specs/consensus/quint/statemachineAsync.qnt
=> fix(spec): agreement for multiple heights

specs/consensus/overview.md
=> feat(spec): discussion of consensus `getValue()` function

docs/tutorials/channels.md
Fixes versions mismatch in [docs/tutorials/channels.md](https://github.com/OakenKnight/malachite/blob/main/docs/tutorials/channels.md)
---
=> fix(docs): fixed versions in tutorials/channels.md

.github/workflows/todo-tracking.yml, scripts/todos.py
=> chore(ci): Add tracking of TODOs and FIXMEs in CI

specs/consensus/overview.md
Part of #761.
Rendered [section](https://github.com/informalsystems/malachite/blob/cason/761-broadcast/specs/consensus/overview.md#network)
---
=> feat(spec): Consensus network requirements and gossip property

specs/consensus/overview.md
Part of #761.
Rendered [section](https://github.com/informalsystems/malachite/blob/cason/761-timeouts/specs/consensus/overview.md#timeouts).
Probably it is better to merge this PR after PR #764.
---
=> feat(spec): Consensus timeouts and synchrony assumptions

docs/tutorials/channels.md
This PR resolves the inconsistency in Malachite dependencies in the tutorial. Since `informalsystems-malachitebft-test` is not published on `crates.io`, all related crates are now pulled directly from the Malachite's git repository.
---
=> fix(docs): Add git dependencies in tutorial

code/crates/app/src/lib.rs, code/examples/channel/src/state.rs
Addresses TODO on [/code/crates/app/src/lib.rs](https://github.com/informalsystems/malachite/tree/9b65e23e7235cad02c007adb988fd9984a5bb5c6/code/crates/app/src/lib.rs#L25). In [types.rs](https://github.com/informalsystems/malachite/blob/9b65e23e7235cad02c007adb988fd9984a5bb5c6/code/crates/app/src/types.rs#L6) there was already `use` for said `struct`, so I removed it.
---
=> feat(code): removed unnecessary `use`

code/crates/app-channel/src/msgs.rs, code/crates/core-consensus/src/util/pretty.rs, code/crates/core-types/src/context.rs, code/crates/core-types/src/lib.rs, code/crates/core-types/src/signing.rs, code/crates/core-types/src/vote.rs, code/crates/core-types/src/vote_extension.rs, code/crates/engine/src/consensus.rs, code/crates/engine/src/host.rs, code/crates/starknet/host/src/actor.rs, code/crates/starknet/host/src/codec.rs, code/crates/starknet/host/src/host/starknet.rs, code/crates/starknet/p2p-types/src/context.rs, code/crates/starknet/p2p-types/src/signing/provider.rs, code/crates/starknet/p2p-types/src/vote.rs, code/crates/test/src/codec/proto/mod.rs, code/crates/test/src/context.rs, code/crates/test/src/signing.rs
Add the following associated type to the `Context`:
```rust
type Extension: Extension;
```
where `Extension` is defined as
```rust
pub trait Extension
where
Self: Clone + Debug + Eq + Send + Sync + 'static,
{
/// Returns the size of the extension in bytes.
fn size_bytes(&self) -> usize;
}
```
Implementations of `Extension` are provided for the following types:
- `()`
- `Vec<u8>`
- `Bytes`
- `[u8; N]`
=> feat(code): Abstract over vote extension type

code/crates/core-driver/src/driver.rs, code/crates/starknet/p2p-types/src/validator_set.rs, code/crates/test/src/validator_set.rs
- Addresses the TODO on [/code/crates/core-driver/src/driver.rs](https://github.com/informalsystems/malachite/blob/9b65e23e7235cad02c007adb988fd9984a5bb5c6/code/crates/core-driver/src/driver.rs#L69).
- Removes unused functions: `add()`, `update()`, and `remove()`. 
- Adapts and renames the `add_update_remove()` test to `new_validator_set_vp()`.
---
=> feat(code): Wrap `Vec<Validator>` into `Arc` in `ValidatorSet` struct

code/crates/core-state-machine/src/input.rs
`PrecommitValue` is not used anywhere in the code. The comment references line 51, which is actually part of line 49, covered already by input `ProposalAndPrecommitValue`.
=> chore: Remove unused PrecommitValue from Input

code/crates/starknet/host/src/mempool.rs
Addresses FIXME on [/code/crates/starknet/host/src/mempool.rs](https://github.com/informalsystems/malachite/blob/1947b34fafbe372e66a45b06c05d13a5f64f6f3a/code/crates/starknet/host/src/mempool.rs#L220)
---
=> feat(code/app/starknet): Include existing transactions when reaping the mempool not just the ones generated on the fly

code/crates/app-channel/src/run.rs, code/crates/app/src/node.rs, code/crates/app/src/spawn.rs, code/crates/core-consensus/tests/full_proposal.rs, code/crates/core-driver/tests/it/basic.rs, code/crates/core-driver/tests/it/extra.rs, code/crates/core-types/src/context.rs, code/crates/core-types/src/signing.rs, code/crates/engine/src/consensus.rs, code/crates/starknet/host/src/node.rs, code/crates/starknet/host/src/spawn.rs, code/crates/starknet/p2p-types/src/context.rs, code/crates/test/src/context.rs, code/crates/test/src/node.rs, code/examples/channel/src/node.rs, code/examples/channel/src/state.rs
The `Context` should not concern itself with signing as the core consensus library does not sign nor verify signatures itself, but rather does so via effects.
The `SigningProvider` trait is still used in the `engine` crate for signing messages and verifying signatures, but should eventually be removed in favor of `HostMsg` pertaining to verification.
=> chore(code): Move `SigningProvider` out of `Context`

code/crates/core-consensus/src/handle/vote.rs, code/crates/core-consensus/src/types.rs
=> fix(code/core-consensus): Verify vote extension on precommits

code/crates/engine/src/consensus.rs
Closes: #XXX
Bits from initial work on #771
---
=> chore(code): Early check for sync actor presence

code/crates/core-consensus/src/handle/timeout.rs, code/crates/engine/src/consensus.rs, code/crates/engine/src/util/events.rs, code/crates/engine/src/wal/entry.rs, code/crates/engine/src/wal/thread.rs, code/crates/starknet/test/src/lib.rs, code/crates/starknet/test/src/tests/vote_sync.rs, code/crates/starknet/test/src/tests/wal.rs
Closes: #XXX
Sometime wal entries fail to decode with errors like this:
```
2025-02-07T20:30:44.054030Z ERROR node{moniker=test-2}:wal{height=144}: Failed to decode WAL entry 4: failed to fill whole buffer
```
Looks like for `PrevoteTimeLimit` and `PrecommitTimeLimit` we still write something to the WAL (just the tag) and later fail to decode.
Note: A better fix might be to move the entry filtering logic in consensus who would decide which entries should be logged. For timeouts it could check the type [here](https://github.com/informalsystems/malachite/blob/fec4b6ed39637db75d742a7bf002eb9b56008e9f/code/crates/engine/src/consensus.rs#L1049-L1053)
---
[gh-edit-branch]: …
=> chore(code): Some WAL entries fail to decode

code/crates/test/app/src/streaming.rs, code/examples/channel/src/streaming.rs
=> fix(code/app): Fix bug in test app and example app where proposal parts were not always processed in order of sequence number

code/Cargo.lock, code/crates/engine/Cargo.toml, code/crates/engine/src/consensus.rs, code/crates/engine/src/util/mod.rs, code/crates/engine/src/util/msg_buffer.rs
> @ancazamfir: Votes may be processed before WAL replay (https://github.com/informalsystems/malachite/issues/850#issuecomment-2659910086)
---
This PR introduces message buffering for the consensus engine during startup and recovery phases. This is an important improvement to handle messages that arrive before the consensus engine is fully started or while it is recovering state via the WAL.
- Add a `VecDeque` buffer to store messages that arrive during `Unstarted`/`Recovering` phases
- Implement a message filtering function to determine which messages should be buffered
- Add processing of buffered messages once consensus starts
- Set a maximum buffer size of 1024 messages to prevent unbounded memory growth
Messages that should be buffered include votes, proposals, and proposal parts. …
=> feat(code/engine): Buffer consensus messages during startup and recovery

CONTRIBUTING.md, CONTRIBUTING_CODE.md, code/.cargo/config.toml, code/.config/nextest.toml
=> chore: Add detailed contributing informations

code/Cargo.toml, code/clippy.toml, code/crates/engine/src/network.rs, code/crates/engine/src/util/mod.rs, code/crates/engine/src/util/output_port.rs, code/crates/engine/src/util/timers.rs, code/crates/starknet/host/src/mempool/network.rs
See `https://github.com/slawlor/ractor/issues/225` for background info
With this PR, the OutputPort will log a warning if it runs into backpressure issues and drops messages.
It also bumps the capacity of the network output port from 10 to 128 and the one for timers from 10 to 64.
---
=> fix(code/engine): Use custom version of `OutputPort` with configurable capacity

code/crates/config/src/lib.rs, code/crates/discovery/src/handlers/close.rs, code/crates/discovery/src/handlers/connect_request.rs, code/crates/discovery/src/handlers/dial.rs, code/crates/discovery/src/handlers/extension.rs, code/crates/discovery/src/handlers/helpers.rs, code/crates/discovery/src/handlers/identify.rs, code/crates/discovery/src/handlers/peers_management.rs, code/crates/discovery/src/handlers/peers_request.rs, code/crates/discovery/src/handlers/selection/selector.rs, code/crates/discovery/src/lib.rs, code/crates/network/src/lib.rs, code/crates/network/test/src/lib.rs, code/crates/network/test/tests/discovery.rs, code/crates/starknet/test/src/lib.rs
Closes: #886 and #887
Now, when discovery is disabled, all connections are directly persistent. The maximum number of connections allowed is defined in the configuration with the `num_inbound_peers` parameter.
Moreover, the logs in the discovery crate have been reduced to mainly debug verbosity, leaving the most relevant logs as info verbosity.
---
=> fix(code/discovery): Simplified disabled discovery + reduced logs verbosity

code/crates/app-channel/src/run.rs, code/crates/engine/src/consensus.rs, code/crates/engine/src/wal.rs, code/crates/engine/src/wal/thread.rs
Closes: #888 
```
INFO  node{moniker=app-2}:consensus{height=1 round=0}: Starting new height height=2
INFO  node{moniker=app-2}:consensus{height=1 round=0}: Starting new round height=2 round=0 proposer=CC15EF77...
DEBUG node{moniker=app-2}:wal{height=1}: Flushed WAL to disk wal.entries=7 wal.size=821
DEBUG node{moniker=app-2}:wal{height=1}: Reset WAL height=2
DEBUG node{moniker=app-2}:consensus{height=1 round=0}: No WAL entries to replay height=2
```
```
INFO  node{moniker=app-2}:consensus{height=2 round=0}: Starting new height height=2
INFO  node{moniker=app-2}:consensus{height=2 round=0}: Starting new round height=2 round=0 proposer=CC15EF77..
DEBUG node{moniker=app-2}:wal{height=1}: Flushed WAL to disk wal.entries=7 wal.size=821
DEBUG node{moniker=app-2}:wal{height=2}: Reset WAL …
```
=> fix(code/engine): Ensure the height in the tracing span matches the height we are about to start

code/crates/app-channel/src/msgs.rs, code/crates/core-consensus/src/handle/driver.rs, code/crates/core-consensus/src/state.rs, code/crates/core-driver/src/driver.rs, code/crates/core-driver/src/mux.rs, code/crates/starknet/test/src/tests/value_sync.rs, code/crates/test/app/src/app.rs, code/crates/test/app/src/node.rs, code/crates/test/app/src/state.rs, code/crates/test/app/src/store.rs, code/crates/test/framework/src/params.rs, code/crates/test/proto/consensus.proto, code/crates/test/src/proposal_part.rs, code/crates/test/tests/it/main.rs, code/crates/test/tests/it/n3f0.rs, code/crates/test/tests/it/n3f0_consensus_mode.rs, code/crates/test/tests/it/value_sync.rs, code/crates/test/tests/it/vote_sync.rs, code/crates/test/tests/it/vote_sync_bcast.rs, code/crates/test/tests/it/wal.rs, code/examples/channel/src/app.rs, code/examples/channel/src/node.rs, code/examples/channel/src/state.rs, code/examples/channel/src/store.rs, code/scripts/spawn.bash
Closes: #XXX
Changes driver code to vote equivocate on first round of initial height when proposer. No configuration flag yet and a lot of tests will timeout
The tests we want to pass in an initial iteration are:
```
cargo run --bin informalsystems-malachitebft-example-channel -- testnet --nodes 3 --home nodes
export APP_BINARY="informalsystems-malachitebft-example-channel"; ./scripts/spawn.bash --nodes 3 --home nodes
```
```
cargo run --bin informalsystems-malachitebft-starknet-app -- testnet --nodes 3 --home nodes
export APP_BINARY="informalsystems-malachitebft-starknet-app"; ./scripts/spawn.bash --nodes 3 --home nodes
```
```
cargo nextest run -p informalsystems-malachitebft-test --no-capture --retries 0 n3f0::all_correct_nodes
```
Notes:
- we need to figure out a better way to trigger …
=> feat(code): Polka test and fixes

code/Cargo.lock, code/crates/app/Cargo.toml, code/crates/app/src/lib.rs, code/crates/engine/src/wal.rs, code/crates/engine/src/wal/iter.rs, code/crates/engine/src/wal/thread.rs, code/crates/starknet/app/src/main.rs, code/crates/starknet/host/src/codec.rs, code/crates/test/cli/src/args.rs, code/crates/test/cli/src/cmd/dump_wal.rs, code/crates/test/cli/src/cmd/mod.rs, code/crates/test/src/codec/proto/mod.rs, code/examples/channel/src/main.rs
This PR adds a `dump-wal` command to the test CLI which can dump all entries found in a given WAL file.
It also adds a new `Dump` message to the WAL actor which instructs it to dump the WAL to the console. This message is not used yet but maybe we can come up with a set of conditions which would trigger it?
---
=> feat(code/wal): Add facilities for dumping the WAL entries

code/crates/core-consensus/src/handle/vote.rs, code/crates/core-votekeeper/src/keeper.rs
Before adding a vote in the WAL, check that we have not yet seen it, ie. that it has not yet been tallied in the vote keeper.
This avoids the situation where a node is stuck, repeatedly asks for votes via vote sync but cannot make progress, and ends up with a lot of duplicate votes in the WAL.
---
=> fix(code/core-consensus): Only persist votes in the WAL if they have not yet been seen

code/crates/config/src/lib.rs, code/crates/core-consensus/src/handle/proposed_value.rs, code/crates/core-driver/src/driver.rs, code/crates/core-state-machine/src/output.rs, code/crates/core-state-machine/src/state.rs, code/crates/core-state-machine/src/state_machine.rs, code/crates/core-types/src/context.rs, code/crates/starknet/p2p-types/src/context.rs, code/crates/test/Cargo.toml, code/crates/test/app/src/app.rs, code/crates/test/app/src/node.rs, code/crates/test/framework/src/logging.rs, code/crates/test/framework/src/node.rs, code/crates/test/mbt/src/tests/consensus/runner.rs, code/crates/test/src/context.rs, code/crates/test/src/lib.rs, code/crates/test/src/middleware.rs, code/crates/test/tests/it/main.rs, code/crates/test/tests/it/wal.rs, code/examples/channel/src/node.rs
Add a `Middleware` to the `TestContext` to override how votes and proposals are built, allowing us to change what a node votes or proposes on a per-test basis.
This was extracted from https://github.com/informalsystems/malachite/pull/896 to make it easier to review that PR.
---
* Make `new_prevote`, `new_precommit` and `new_proposal` methods of `Context` instead of static functions
* Stuff middleware in the `TestContext` instead of static variable
* Remove unused dependency
* Add way to access middleware from TestContext
---
[gh-edit-branch]: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maint …
=> feat(code/test): Middleware for testing

code/crates/core-consensus/src/handle/decide.rs, code/crates/core-consensus/src/state.rs
=> chore(code): Remove decided_sent guard from consensus state

README.md
Closes: #1026
This PR proposes a small cosmetic improvement that should be quick to review. It's a very low-priority change — more of a low-hanging fruit — and shouldn't take focus away from core work. The goal is simply to improve how the crate appears on [crates.io](https://crates.io/), giving it a slightly more polished and professional look. 
The banner image renders well [on my branch](https://github.com/informalsystems/malachite/tree/andy/1026-crates-banner), and since this is an absolute URL is should work in crates.io too (but not sure if will fix once this is merged or only when a new release for a crate is published)
---
[gh-edit-branch]: https://docs.github.com/en/pull-requests/collaborating-with-pull-request …
=> fix(crates): broken banner on all Malachite crates in crates.io

.github/workflows/coverage.yml, .github/workflows/docs.yml, .github/workflows/mbt.yml, .github/workflows/publish.yml, .github/workflows/rust.yml, .github/workflows/semver.yml, CONTRIBUTING_CODE.md, code/Cargo.lock, code/Cargo.toml, code/crates/starknet/p2p-proto/Cargo.toml, code/crates/starknet/p2p-proto/build.rs, code/crates/test/Cargo.toml, code/crates/test/build.rs, code/crates/test/mempool/Cargo.toml, code/crates/test/mempool/build.rs, code/examples/channel/README.md, docs/testing/local.md
This PR removes the dependency on `protoc`, instead using [`protox`](https://lib.rs/protox) to compile the Protobuf definitions to file descriptors and have those compiled to Rust code by `prost`. This simplifies the setup for contributors, app builders and the CI.
---
=> chore: Remove dependency on `protoc`, use the `protox` crate instead

code/crates/engine/src/consensus.rs
Fix the code not to pass the value response in case the commit certificate associated with it is invalid. 
=> fix(code): Don't pass the sync response to the app when the commit certificate is invalid

.github/workflows/qa.yml
This reverts commit 100350859fd6ca4bd115f3eb97a7f04c6b8179ee. Mainly, the default branch option on GitHub is not enough as it points to the branch of the workflow, and we need to run the workflow from the main branch, but using the code from another branch.
=> fix(qa): Revert the commit where we removed the branch option from the QA.

.github/workflows/qa.yml, qa/terraform/project.tf, qa/terraform/scripts/average_runs.py, qa/terraform/scripts/average_runs_test.py, qa/terraform/scripts/format_csv_file.py
This PR adds support for running multiple QA experiments (N runs) through the GitHub workflow. Each run is stored individually on S3, and the averaged results are automatically published to the Malachite website dashboard.
=> feat(qa): Run QA experiments multiple times and publish the average results

RELEASE_NOTES.md, code/crates/engine/src/consensus.rs
Closes: #1135
Part of: https://github.com/informalsystems/malachite/issues/1136
---
=> fix(code/sync): Use proposer of synced value instead of our own address for `ProcessSyncedValue`

qa/docker/Dockerfile
Without this we get such failures when running QA:
```#14 [builder 3/4] WORKDIR /mnt
#15 [builder 4/4] RUN --mount=type=bind,from=code,target=/mnt cargo build --release --target-dir /tmp
#15 0.273     Updating crates.io index
#15 2.883 error: failed to write /mnt/Cargo.lock
#15 2.883 
#15 2.883 Caused by:
#15 2.883   failed to open: /mnt/Cargo.lock
#15 2.883 
#15 2.883 Caused by:
#15 2.883   Read-only file system (os error 30)
```
https://github.com/informalsystems/malachite/actions/runs/16723245984/job/47332329264
=> fix(qa): Mount source directory as read-write

code/crates/test/src/validator_set.rs, code/crates/wal/src/log.rs
Closes: #XXX
CI is failing with `mismatched-lifetime-syntaxes` lint errors in the WAL and test crates, add explicit annotations.
---
=> chore(code): Add explicit annotations for mismatched-lifetime-syntaxes lint

code/crates/core-consensus/src/handle/liveness.rs, code/crates/core-consensus/src/handle/proposal.rs, code/crates/core-consensus/src/handle/proposed_value.rs, code/crates/core-consensus/src/handle/start_height.rs, code/crates/core-consensus/src/handle/sync.rs, code/crates/core-consensus/src/handle/vote.rs, code/crates/core-consensus/src/state.rs, code/crates/core-consensus/src/util/bounded_queue.rs, code/crates/metrics/src/metrics.rs
> [!NOTE]
> 📚 Stacked on top of #1188 
Closes: #XXX
Add two new metrics:
- `malachitebft_core_consensus_queue_heights`: The number of distinct heights there are inputs for in the queue
- `malachitebft_core_consensus_queue_size`: The total number of inputs in the queue
---
=> feat(code/metrics): Add metrics for consensus input queue
